language: elixir
elixir:
  - 1.3.4
  - 1.4.2
otp_release:
  - 18.3
  - 19.2
before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - travis_wait mix dialyzer --plt
script:
  - mix coveralls.travis
  - # skip dialyzer for elixir 1.4 and erlang 18 as it produces weird errors, see #69
  - if ! ([[ "$TRAVIS_ELIXIR_VERSION" == "1.4"* ]] && [[ "$TRAVIS_OTP_RELEASE" == "18"* ]]); then mix dialyzer --halt-exit-status; fi
cache:
  directories:
    - _build
    - deps
